// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.15.5
// source: messages.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// ParseMode determines how the message should be parsed
type ParseMode int32

const (
	ParseMode_PLAIN       ParseMode = 0
	ParseMode_HTML        ParseMode = 1
	ParseMode_MARKDOWN    ParseMode = 2
	ParseMode_MARKDOWN_V2 ParseMode = 3
)

// Enum value maps for ParseMode.
var (
	ParseMode_name = map[int32]string{
		0: "PLAIN",
		1: "HTML",
		2: "MARKDOWN",
		3: "MARKDOWN_V2",
	}
	ParseMode_value = map[string]int32{
		"PLAIN":       0,
		"HTML":        1,
		"MARKDOWN":    2,
		"MARKDOWN_V2": 3,
	}
)

func (x ParseMode) Enum() *ParseMode {
	p := new(ParseMode)
	*p = x
	return p
}

func (x ParseMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseMode) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (ParseMode) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x ParseMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseMode.Descriptor instead.
func (ParseMode) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// InMessage is the model for received messages
type InMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Message ID
	MessageId int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Chat ID
	ChatId int64 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Sender ID
	SenderId int64 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Time
	Time *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	// True if message was sent in a private chat (1:1 with the bot); false if it's in a group or channel
	Private bool `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`
	// Text
	Text string `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *InMessage) Reset() {
	*x = InMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessage) ProtoMessage() {}

func (x *InMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessage.ProtoReflect.Descriptor instead.
func (*InMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *InMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *InMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *InMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *InMessage) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *InMessage) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

func (x *InMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// OutMessage is the model for messages that need to be sent
type OutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Recipient (chat or user)
	Recipient string `protobuf:"bytes,1,opt,name=recipient,proto3" json:"recipient,omitempty"`
	// Message to reply to (if any)
	ReplyTo int64 `protobuf:"varint,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	// Message could be text or file (and photo, etc)
	//
	// Types that are assignable to Content:
	//	*OutMessage_Text
	//	*OutMessage_File
	//	*OutMessage_Photo
	Content isOutMessage_Content `protobuf_oneof:"content"`
	// Option: disable notifications
	DisableNotification bool `protobuf:"varint,21,opt,name=disable_notification,json=disableNotification,proto3" json:"disable_notification,omitempty"`
	// Option: disable web page preview
	DisableWebPagePreview bool `protobuf:"varint,22,opt,name=disable_web_page_preview,json=disableWebPagePreview,proto3" json:"disable_web_page_preview,omitempty"`
}

func (x *OutMessage) Reset() {
	*x = OutMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessage) ProtoMessage() {}

func (x *OutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessage.ProtoReflect.Descriptor instead.
func (*OutMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *OutMessage) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *OutMessage) GetReplyTo() int64 {
	if x != nil {
		return x.ReplyTo
	}
	return 0
}

func (m *OutMessage) GetContent() isOutMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *OutMessage) GetText() *OutTextMessage {
	if x, ok := x.GetContent().(*OutMessage_Text); ok {
		return x.Text
	}
	return nil
}

func (x *OutMessage) GetFile() *OutFileMessage {
	if x, ok := x.GetContent().(*OutMessage_File); ok {
		return x.File
	}
	return nil
}

func (x *OutMessage) GetPhoto() *OutPhotoMessage {
	if x, ok := x.GetContent().(*OutMessage_Photo); ok {
		return x.Photo
	}
	return nil
}

func (x *OutMessage) GetDisableNotification() bool {
	if x != nil {
		return x.DisableNotification
	}
	return false
}

func (x *OutMessage) GetDisableWebPagePreview() bool {
	if x != nil {
		return x.DisableWebPagePreview
	}
	return false
}

type isOutMessage_Content interface {
	isOutMessage_Content()
}

type OutMessage_Text struct {
	Text *OutTextMessage `protobuf:"bytes,10,opt,name=text,proto3,oneof"`
}

type OutMessage_File struct {
	File *OutFileMessage `protobuf:"bytes,11,opt,name=file,proto3,oneof"`
}

type OutMessage_Photo struct {
	Photo *OutPhotoMessage `protobuf:"bytes,12,opt,name=photo,proto3,oneof"`
}

func (*OutMessage_Text) isOutMessage_Content() {}

func (*OutMessage_File) isOutMessage_Content() {}

func (*OutMessage_Photo) isOutMessage_Content() {}

// OutTextMessage is the model for text messages that need to be sent
type OutTextMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Text of the message
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// How the message should be parsed
	ParseMode ParseMode `protobuf:"varint,2,opt,name=parse_mode,json=parseMode,proto3,enum=bot.ParseMode" json:"parse_mode,omitempty"`
}

func (x *OutTextMessage) Reset() {
	*x = OutTextMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutTextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutTextMessage) ProtoMessage() {}

func (x *OutTextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutTextMessage.ProtoReflect.Descriptor instead.
func (*OutTextMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *OutTextMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutTextMessage) GetParseMode() ParseMode {
	if x != nil {
		return x.ParseMode
	}
	return ParseMode_PLAIN
}

// OutPhotoMessage is the model for file messages that need to be sent
type OutFileMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Location of the file
	//
	// Types that are assignable to Location:
	//	*OutFileMessage_Url
	//	*OutFileMessage_LocalPath
	//	*OutFileMessage_Data
	Location isOutFileMessage_Location `protobuf_oneof:"location"`
}

func (x *OutFileMessage) Reset() {
	*x = OutFileMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutFileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutFileMessage) ProtoMessage() {}

func (x *OutFileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutFileMessage.ProtoReflect.Descriptor instead.
func (*OutFileMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (m *OutFileMessage) GetLocation() isOutFileMessage_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (x *OutFileMessage) GetUrl() string {
	if x, ok := x.GetLocation().(*OutFileMessage_Url); ok {
		return x.Url
	}
	return ""
}

func (x *OutFileMessage) GetLocalPath() string {
	if x, ok := x.GetLocation().(*OutFileMessage_LocalPath); ok {
		return x.LocalPath
	}
	return ""
}

func (x *OutFileMessage) GetData() []byte {
	if x, ok := x.GetLocation().(*OutFileMessage_Data); ok {
		return x.Data
	}
	return nil
}

type isOutFileMessage_Location interface {
	isOutFileMessage_Location()
}

type OutFileMessage_Url struct {
	// Retrieve from a URL on the Internet
	Url string `protobuf:"bytes,1,opt,name=url,proto3,oneof"`
}

type OutFileMessage_LocalPath struct {
	// Load from the local disk
	LocalPath string `protobuf:"bytes,2,opt,name=local_path,json=localPath,proto3,oneof"`
}

type OutFileMessage_Data struct {
	// Embedded binary data
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3,oneof"`
}

func (*OutFileMessage_Url) isOutFileMessage_Location() {}

func (*OutFileMessage_LocalPath) isOutFileMessage_Location() {}

func (*OutFileMessage_Data) isOutFileMessage_Location() {}

// OutPhotoMessage is the model for photo messages that need to be sent
type OutPhotoMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This "extends" OutFileMessage
	File *OutFileMessage `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// Size: width
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// Size: height
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Caption
	Caption string `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	// Caption parse mode
	CaptionParseMode ParseMode `protobuf:"varint,5,opt,name=caption_parse_mode,json=captionParseMode,proto3,enum=bot.ParseMode" json:"caption_parse_mode,omitempty"`
}

func (x *OutPhotoMessage) Reset() {
	*x = OutPhotoMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutPhotoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutPhotoMessage) ProtoMessage() {}

func (x *OutPhotoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutPhotoMessage.ProtoReflect.Descriptor instead.
func (*OutPhotoMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *OutPhotoMessage) GetFile() *OutFileMessage {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *OutPhotoMessage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *OutPhotoMessage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *OutPhotoMessage) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *OutPhotoMessage) GetCaptionParseMode() ParseMode {
	if x != nil {
		return x.CaptionParseMode
	}
	return ParseMode_PLAIN
}

// SentMessage contains the IDs of a message that was sent by the methods to send messages
type SentMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Message ID
	MessageId int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Chat ID
	ChatId int64 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *SentMessage) Reset() {
	*x = SentMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentMessage) ProtoMessage() {}

func (x *SentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentMessage.ProtoReflect.Descriptor instead.
func (*SentMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *SentMessage) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SentMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

// EditTextMessage is used to edit a text message that was sent earlier
type EditTextMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ID of the message that was sent
	Message *SentMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Content
	Text *OutTextMessage `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	// Option: disable web page preview
	DisableWebPagePreview bool `protobuf:"varint,22,opt,name=disable_web_page_preview,json=disableWebPagePreview,proto3" json:"disable_web_page_preview,omitempty"`
}

func (x *EditTextMessage) Reset() {
	*x = EditTextMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTextMessage) ProtoMessage() {}

func (x *EditTextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTextMessage.ProtoReflect.Descriptor instead.
func (*EditTextMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *EditTextMessage) GetMessage() *SentMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *EditTextMessage) GetText() *OutTextMessage {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *EditTextMessage) GetDisableWebPagePreview() bool {
	if x != nil {
		return x.DisableWebPagePreview
	}
	return false
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x62, 0x6f, 0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x09, 0x49, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xc0, 0x02, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x12,
	0x29, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x62, 0x6f, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x4f,
	0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x31, 0x0a, 0x14, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x15, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x18, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x18, 0x16, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c,
	0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x42,
	0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x0e, 0x4f, 0x75,
	0x74, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x2d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x70, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22,
	0x67, 0x0a, 0x0e, 0x4f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x0a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc0, 0x01, 0x0a, 0x0f, 0x4f, 0x75, 0x74,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x6f, 0x74,
	0x2e, 0x4f, 0x75, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a,
	0x12, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x62, 0x6f, 0x74, 0x2e,
	0x50, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x10, 0x63, 0x61, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x22, 0x45, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74,
	0x49, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x0f, 0x45, 0x64, 0x69, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x53, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x62, 0x6f, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x54, 0x65, 0x78, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x37, 0x0a, 0x18, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x77, 0x65, 0x62, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x16, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x57, 0x65, 0x62, 0x50, 0x61, 0x67, 0x65, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x2a, 0x3f, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x73, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x48, 0x54, 0x4d, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f,
	0x57, 0x4e, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f, 0x57, 0x4e,
	0x5f, 0x56, 0x32, 0x10, 0x03, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x49, 0x74, 0x61, 0x6c, 0x79, 0x50, 0x61, 0x6c, 0x65, 0x41, 0x6c, 0x65,
	0x2f, 0x72, 0x73, 0x73, 0x2d, 0x62, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_messages_proto_goTypes = []interface{}{
	(ParseMode)(0),                // 0: bot.ParseMode
	(*InMessage)(nil),             // 1: bot.InMessage
	(*OutMessage)(nil),            // 2: bot.OutMessage
	(*OutTextMessage)(nil),        // 3: bot.OutTextMessage
	(*OutFileMessage)(nil),        // 4: bot.OutFileMessage
	(*OutPhotoMessage)(nil),       // 5: bot.OutPhotoMessage
	(*SentMessage)(nil),           // 6: bot.SentMessage
	(*EditTextMessage)(nil),       // 7: bot.EditTextMessage
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_messages_proto_depIdxs = []int32{
	8, // 0: bot.InMessage.time:type_name -> google.protobuf.Timestamp
	3, // 1: bot.OutMessage.text:type_name -> bot.OutTextMessage
	4, // 2: bot.OutMessage.file:type_name -> bot.OutFileMessage
	5, // 3: bot.OutMessage.photo:type_name -> bot.OutPhotoMessage
	0, // 4: bot.OutTextMessage.parse_mode:type_name -> bot.ParseMode
	4, // 5: bot.OutPhotoMessage.file:type_name -> bot.OutFileMessage
	0, // 6: bot.OutPhotoMessage.caption_parse_mode:type_name -> bot.ParseMode
	6, // 7: bot.EditTextMessage.message:type_name -> bot.SentMessage
	3, // 8: bot.EditTextMessage.text:type_name -> bot.OutTextMessage
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutTextMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutFileMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutPhotoMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTextMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OutMessage_Text)(nil),
		(*OutMessage_File)(nil),
		(*OutMessage_Photo)(nil),
	}
	file_messages_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*OutFileMessage_Url)(nil),
		(*OutFileMessage_LocalPath)(nil),
		(*OutFileMessage_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
